// <auto-generated />
namespace projectk.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addlikefb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlikefb));
        
        string IMigrationMetadata.Id
        {
            get { return "201306051605026_addlikefb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
